### ISSUE TITLE
Remove and update the fields of vehicle register form

### ISSUE THREAD

**Issue by MaduRanasinghe** [lk-gov-health-hiu/fmis#43]
Keep the following fields only

Vehicle Number -> Type -Text
Institution -> Automatically capture the institution by the system user's institution, possible to change if needed
Vehicle Type -> List - (Bus, Car, Van, Jeep, Lorry, Ambulance, Cab, Three Wheeler, Generator)
Vehicle Name -> List - (Toyota, Nissan, Mitsubishi, Bens, Isuzu, Ford, Other)

**Comment by buddhika75** [comment]
Vehicle Name NOT required

**Comment by MaduRanasinghe** [comment]
DDG Logistic stated that it is necessary to identify vehicles

**Comment by buddhika75** [comment]
Done
